### ISSUE TITLE
Software to labelize your images

### ISSUE THREAD

**Issue by Kmarconi** [jkjung-avt/hand-detection-tutorial#32]
Hi, I was wondering which software you were using to labelize your images because the format of your txt files ( hand 0 0 0 515 431 623 544 0 0 0 0 0 0 0 0 for example) do not look like the ones I have with LabelImg soft. 

Thanks for your repo again :)

**Comment by Kmarconi** [comment]
I'm asking this question because I'm working on adapting your hand detection project to another object detection project. After making my config, train.sh files, I need to make my dataset so I collected 700 hundred images (not that much but will start with this) and I was wondering if I need my txt label files to have the same structure as yours ?

**Comment by jkjung-avt** [comment]
The original "egohands" annotations are in MATLAB format.  I converted it to KITTI format simply because I was more familiar with that format at that time.

If you reference tensorflow object detection API source code, you could find scripts to convert datasets in various annotation formats to TFRecords: https://github.com/tensorflow/models/tree/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/dataset_tools

[labelImg](https://github.com/tzutalin/labelImg) saves annotations in Pascal VOC format.  So you could use [create_pascal_tf_record.py](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/dataset_tools/create_pascal_tf_record.py) instead of create_kitti_tf_record.py in [create_tfrecords.sh](https://github.com/jkjung-avt/hand-detection-tutorial/blob/master/create_tfrecords.sh#L4).  Note that you might also need to modify the input/output paths in the scripts.

**Comment by Kmarconi** [comment]
Thanks !
